import type { Metadata } from 'next'
import Global from './lib/provider/emotion'
import globals from './lib/styles/global'


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Global styles={globals} />
        {children}</body>
    </html>
  )
}
